package com.tcay.slalom.UI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.tcay.slalom.Race;
import com.tcay.slalom.UI.tables.RunScoringTable;

import javax.swing.*;

/**
 * Created with IntelliJ IDEA.
 * User: allen
 * Date: 9/28/13
 * Time: 6:28 PM
 * To change this template use File | Settings | File Templates.
 */
public class ScoringBoard {
    private JPanel panel1;
    private JScrollPane leaderScrollPane;
    private JTable runScoringTable;


    public void setData(ScoringBoard data) {
    }

    public void getData(ScoringBoard data) {
    }

    public boolean isModified(ScoringBoard data) {
        return false;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
//        resultsTable  = new JBTable();

        runScoringTable = new RunScoringTable().createTable();
        leaderScrollPane = new JScrollPane();
        Race.getInstance().updateResults();


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        CellConstraints cc = new CellConstraints();
        panel1.add(leaderScrollPane, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        leaderScrollPane.setViewportView(runScoringTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
