package com.tcay.slalom.UI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

/**
 * Created with IntelliJ IDEA.
 * User: allen
 * Date: 10/13/13
 * Time: 8:53 AM
 * To change this template use File | Settings | File Templates.
 */
public class TestScrollPane_REFERENCE {
    private JPanel panel1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow"));
        final JScrollPane scrollPane1 = new JScrollPane();





        CellConstraints cc = new CellConstraints();
        panel1.add(scrollPane1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        scrollPane1.setViewportView(panel2);



        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel2.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        panel2.add(label2, cc.xy(1, 3));
        final JLabel label3 = new JLabel();
        label3.setText("Label");
        panel2.add(label3, cc.xy(1, 5));
        final JLabel label4 = new JLabel();
        label4.setText("Label");
        panel2.add(label4, cc.xy(1, 7));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
