/*
 * This file is part of SlalomApp.
 *
 *     SlalomApp is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     SlalomApp is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with SlalomApp.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.tcay.slalom.UI;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * SlalomScoring
 * <p/>
 * Teton Cay Group Inc. 2015
 * <p/>
 * User: allen
 * Date: 5/13/15
 * Time: 8:33 PM
 * Rev:  $rev$
 */
public class TrainingTimingUI {
    private JPanel panel1;
    private JLabel currentTimeSSSdotHH;
    private JLabel racerName;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setBackground(new Color(-16777216));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-65485));
        label1.setText("Current Run");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(1, 1));
        currentTimeSSSdotHH.setBackground(new Color(-16777216));
        currentTimeSSSdotHH.setFont(new Font("MT Extra", Font.BOLD, 72));
        currentTimeSSSdotHH.setForeground(UIManager.getColor("InternalFrame.borderDarkShadow"));
        currentTimeSSSdotHH.setText("999.99");
        panel1.add(currentTimeSSSdotHH, cc.xy(1, 5, CellConstraints.CENTER, CellConstraints.DEFAULT));
        racerName = new JLabel();
        racerName.setForeground(new Color(-65485));
        racerName.setText("Label");
        panel1.add(racerName, cc.xy(1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
